import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { CopyButton } from "@/components/copy-button";
import { Sidebar } from "@/components/sidebar";
import { apiEntries, getApiBySlug } from "@/lib/docs";
export function generateStaticParams() { return apiEntries.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const entry = getApiBySlug((await params).slug); return entry ? { title: entry.name, description: entry.description.en ?? entry.description.zh } : {}; }
export default async function ApiPage({ params }: { params: Promise<{ slug: string }> }) { const entry = getApiBySlug((await params).slug); if (!entry) notFound(); return <main className="mx-auto flex max-w-7xl flex-col gap-8 px-4 py-8 md:flex-row"><Sidebar currentSlug={entry.slug} /><article className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-3"><h1 className="break-all text-3xl font-bold">{entry.name}</h1><CopyButton value={entry.name} /></div><dl className="mt-4 grid gap-2 text-sm sm:grid-cols-[8rem_1fr]"><dt className="font-medium">Availability</dt><dd className="capitalize">{entry.side}</dd><dt className="font-medium">Kind</dt><dd className="capitalize">{entry.kind}</dd>{entry.namespace && <><dt className="font-medium">Namespace</dt><dd className="flex min-w-0 items-start gap-2"><code className="break-all">{entry.namespace}</code><CopyButton value={entry.namespace} /></dd></>}</dl><section className="mt-8"><h2 className="text-xl font-semibold">Description</h2>{entry.description.en && <p className="mt-2">{entry.description.en}</p>}{entry.description.zh && <p lang="zh-CN" className="mt-2 text-slate-600 dark:text-slate-300">{entry.description.zh}</p>}</section><section className="mt-8"><h2 className="text-xl font-semibold">Parameters</h2>{entry.parameters.length ? <div className="mt-3 overflow-x-auto"><table className="w-full min-w-[36rem] border-collapse text-left text-sm"><thead><tr className="border-b dark:border-slate-700"><th className="p-2">Name</th><th className="p-2">Type</th><th className="p-2">Description</th></tr></thead><tbody>{entry.parameters.map((parameter) => <tr key={parameter.name} className="border-b dark:border-slate-800"><td className="p-2 font-mono">{parameter.name}</td><td className="p-2 font-mono">{parameter.type ?? "Unknown"}</td><td className="p-2">{parameter.description?.en ?? parameter.description?.zh ?? "—"}</td></tr>)}</tbody></table></div> : <p className="mt-2 text-slate-500">No parameters are documented.</p>}</section>{entry.related?.length ? <section className="mt-8"><h2 className="text-xl font-semibold">Related APIs</h2><ul>{entry.related.map((slug) => <li key={slug}>{getApiBySlug(slug) ? <Link href={`/api/${slug}`}>{getApiBySlug(slug)?.name}</Link> : <span>{slug} (not in this dataset)</span>}</li>)}</ul></section> : null}<p className="mt-10 border-t pt-4 text-sm text-slate-500 dark:border-slate-800">Source: {entry.source?.url ? <a href={entry.source.url}>{entry.source.title ?? entry.source.url}</a> : entry.source?.title ?? "Source not recorded"}</p></article></main>; }
